version: "3.1"

services:
  server:
    command: "npm run dev"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
  
  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - internal
    environment: 
      - ME_CONFIG_MONGODB_SERVER=${MONGO_URI}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASS}
      - ME_CONFIG_OPTIONS_EDITORTHEME=ayu-dark
